apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-replica
  name: redis-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-replica
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis-replica
    spec:
      containers:
        - args:
            - redis-server
            - --replicaof
            - redis-leader
            - "6379"
            - --dir
            - /tmp
          image: redis
          name: redis-replica
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
